spring.application.name=Store

# ===============================
# Server Config
# ===============================
server.port=8081
#server.port=9090
# ===============================
# Database Config
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/paper_trading?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Kolkata
spring.datasource.username=sneha635
spring.datasource.password=@MethodA#DB_042026@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# ===============================
# JPA Config
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT Config
# ===============================
jwt.secret=MySuperSecretKey1234567890JwtSecurityKey
jwt.expiration=86400000

# ===============================
# Mail Config
# ===============================
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=info@vittpath.com
spring.mail.password=l55KTxErAfUD4+UljMHEVg==
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# ===============================
# Encryption
# ===============================
enable.password.encryption=true
enable.otp.encryption=true

security.encryptor.initVector=lwkvczsubsqzhqtr
security.encryptor.secretKey=uusqhmyizhodqgfedblaplqdjlcsmhxv

# ===============================
# Watchlist Config
# ===============================
max.allowed.watchlist=7

# ===============================
# Kite Config
# ===============================
kite.api.key=ZcMjZskPHDd/OnuBx/6OXwQznqFrjjSx8AA6w5IoChw=
kite.api.secret=Qa1eiWgG3NsvjogcVbfeIwMtncS6CBe5eEeBwHiYyvYSiegCmRtFTTVu9/iVbiCv
kite.user.id=ARV966

# ===============================
# Token Expiry
# ===============================
token.expiry.time=23:50
token.expiary.time.hours=24

cleanup.otp.cron=0 50 23 * * *

# ===============================
# File Upload
# ===============================
file.upload-dir=${user.dir}/uploads/profile/pics/
file.max-size=512000